server:
  servlet:
    context-path: /
    application-display-name: Leads Rabbit MQ
  port: 8083
spring:
  application:
    name: leads-middleware
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /